Update requirements.txt - Prevent nest-of-gold test crash
if Werkzeug version is 3.0+ we get 
```
ImportError: cannot import name 'url_decode' from 'werkzeug.urls'
```
as they have removed all the non-core public APIs v3.0 onwards.
The minimum requirement for flask-login is Werkzeug 2.3.3. Hence the same.